version: "3"

services:

  librarian:
    image: librarian
    hostname: librarian
    container_name: librarian
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    command: /bin/bash -c "python main.py;"
    stdin_open: true
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs
    environment:
      - ENVIRONMENT=development
    restart: always # Reinica sempre que houver algum erro
    ports:
      - 2000:2000 # server http

  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    container_name: ollama
    # command: ollama run llama2
    volumes:
      - .:/code
      - ./ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    ports:
      - 11434:11434
  
  chatbot:
    image: lobehub/lobe-chat
    hostname: chatbot
    container_name: chatbot
    volumes:
      - .:/code
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_PROXY_URL=http://host.docker.internal:11434/v1
    restart: always
    ports:
      - 3210:3210
