version: "3"

services:

  sibila:
    image: sibila
    hostname: sibila
    container_name: sibila
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=development
    restart: always # Reinica sempre que houver algum erro
    ports:
      - 8080:8080 # server http

  chromadb:
    image: chromadb/chroma
    hostname: chromadb
    container_name: chromadb
    volumes:
      - ./data/chromadb:/chroma/chroma
    restart: always
    ports:
      - 8000:8000

  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    container_name: ollama
    # command: ollama run llama2
    volumes:
      - .:/code
      - ./ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    ports:
      - 11434:11434
  
  chatbot:
    image: lobehub/lobe-chat
    hostname: chatbot
    container_name: chatbot
    volumes:
      - .:/code
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_PROXY_URL=http://host.docker.internal:11434/v1
    restart: always
    ports:
      - 3210:3210
