version: "3"

services:

  sibila:
    image: sibila
    hostname: sibila
    container_name: sibila
    working_dir: /app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: .
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./src:/app
      - exclude:/app/bin
      - exclude:/app/obj
    restart: always # Reinica sempre que houver algum erro
    ports:
      - 5000:5000

  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    container_name: ollama
    # command: ollama run llama2
    volumes:
      - ./ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    ports:
      - 11434:11434
  
  chatbot:
    image: lobehub/lobe-chat
    hostname: chatbot
    container_name: chatbot
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_PROXY_URL=http://host.docker.internal:11434/v1
    restart: always
    ports:
      - 3210:3210

  # #################################################################################################################
  # POSTGRES
  # #################################################################################################################
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    container_name: postgres
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "vdbms", "-U", "vectoradminuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: vectoradmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vdbms


  # #################################################################################################################
  # CHROMA DB
  # #################################################################################################################
  chromadb:
    image: chromadb/chroma:latest
    hostname: chromadb
    container_name: chromadb
    volumes:
      - ./data/chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=TRUE
    restart: always
    ports:
      - 8000:8000

  # #################################################################################################################
  # VECTOR ADMIN
  # #################################################################################################################
  vector-admin:
    image: mintplexlabs/vectoradmin
    hostname: vector-admin
    container_name: vector-admin
    environment:
      SERVER_PORT: 3001
      DISABLE_TELEMETRY: true
      TZ: America/Los_Angeles
      JWT_SECRET: secret
      SYS_EMAIL: root@vectoradmin.com
      SYS_PASSWORD: password
      INNGEST_EVENT_KEY: background_workers
      INNGEST_SIGNING_KEY: secret
      INNGEST_LANDING_PAGE: true
      DATABASE_CONNECTION_STRING: postgresql://vectoradmin:password@postgres:5432/vdbms
    cap_add:
      - SYS_ADMIN
    restart: always
    ports:
      - 3001:3001
      - 3355:3355
      - 8288:8288
    depends_on:
      - postgres
      - chromadb

volumes:
    exclude: