version: "3"

services:

  rag:
    image: rag
    hostname: rag
    container_name: rag
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs
    environment:
      - ENVIRONMENT=development
    restart: always # Reinica sempre que houver algum erro
    ports:
      - 2000:2000 # server http